name: Docker Image CI

env:
  PROJECT_DIR: Qt_Infortainment_cmake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:  
  build-raspi:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - name: Checkout Source Code
        uses: actions/checkout@v4
        
      - name: Pull Docker Image
        run: docker pull haidinhlv/qtcrossbuild:latest
        
      - name: Compile Application
        run: |
          echo "Starting build process..."
          
          docker run --rm -v ${{ github.workspace }}:/build/project -w /build/project haidinhlv/qtcrossbuild:latest /bin/bash -c "
          
          mkdir -p build_dir output
          
          cd build_dir
          /build/qt6/pi/bin/qt-cmake ../$PROJECT_DIR -DCMAKE_BUILD_TYPE=Debug
          cmake --build . 

          cp /build/project/build_dir/$PROJECT_DIR /build/project/output "
                    
          echo "Build success!"

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: Raspi-Qt-App
          path: output/
